apiVersion: v1
kind: Service
type: LoadBalancer
metadata:
 name: nginx-service
 namespace: my-app
spec:
 selector:
   app: nginx
 ports:
   - protocol: TCP
     port: 80
     targetPort: 80