apiVersion: v1
kind: Service
metadata:
 name: nginx-service
 namespace: my-app
 annotations:
  service.beta.kubernetes.io/aws-load-balancer-type: nlb
  service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Name=ori-nlb, name=ori-nlb
spec:
 type: LoadBalancer
 selector:
   app: nginx
 ports:
   - protocol: TCP
     port: 80
     targetPort: 80
