apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/oritzadok/terraform-argocd-eks.git
    targetRevision: HEAD
    path: "argocd/app"
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      #allowEmpty: false
    syncOptions:
    - CreateNamespace=true